import type { EventType, GiftType, GuestType } from "./types"

// Dados de exemplo para eventos
export const mockEvents: EventType[] = [
  {
    id: "event-1",
    title: "Casamento de João e Maria",
    description:
      "Temos o prazer de convidar você para celebrar nosso casamento. Será uma cerimônia íntima seguida de recepção com jantar e música ao vivo. Esperamos compartilhar este momento especial com você!",
    date: "15/12/2025",
    time: "19:00",
    location: "Espaço Villa Garden, Av. das Flores, 1500, São Paulo",
    coverImage: "/outdoor-wedding-ceremony.png",
    status: "active",
    guestCount: 120,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-20T14:30:00Z",
  },
  {
    id: "event-2",
    title: "Aniversário de 1 ano do Pedro",
    description:
      "Venha celebrar o primeiro aninho do nosso pequeno Pedro! Teremos bolo, doces, brincadeiras e muita diversão para as crianças.",
    date: "20/08/2025",
    time: "15:00",
    location: "Buffet Alegria, Rua dos Sonhos, 123, Rio de Janeiro",
    coverImage: "/placeholder.svg?key=os1i0",
    status: "active",
    guestCount: 50,
    createdAt: "2025-02-10T09:15:00Z",
    updatedAt: "2025-02-12T11:20:00Z",
  },
  {
    id: "event-3",
    title: "Chá de Bebê da Ana",
    description:
      "A família está crescendo! Venha celebrar a chegada da nossa princesinha Sophia em um chá de bebê cheio de amor e carinho.",
    date: "05/07/2025",
    time: "14:30",
    location: "Residência da Família, Rua das Acácias, 789, Belo Horizonte",
    coverImage: "/placeholder.svg?key=kszle",
    status: "draft",
    guestCount: 30,
    createdAt: "2025-03-05T16:40:00Z",
    updatedAt: "2025-03-07T10:10:00Z",
  },
  {
    id: "event-4",
    title: "Chá de Bebê da Ana",
    description:
      "A família está crescendo! Venha celebrar a chegada da nossa princesinha Sophia em um chá de bebê cheio de amor e carinho.",
    date: "05/07/2025",
    time: "14:30",
    location: "Residência da Família, Rua das Acácias, 789, Belo Horizonte",
    coverImage: "/placeholder.svg?key=kszle",
    status: "draft",
    guestCount: 30,
    createdAt: "2025-03-05T16:40:00Z",
    updatedAt: "2025-03-07T10:10:00Z",
  },
]

// Dados de exemplo para presentes
export const mockGifts: GiftType[] = [
  {
    id: "gift-1",
    name: "Jogo de Panelas Tramontina",
    description: "Conjunto de panelas antiaderentes com 5 peças",
    price: "R$ 399,90",
    image: "/cookware-set.png",
    url: "https://www.exemplo.com/produto/1",
    quantity: 1,
    reserved: 1,
    isReservedByMe: true,
    eventId: "event-1",
  },
  {
    id: "gift-2",
    name: "Liquidificador Philips Walita",
    description: "Liquidificador de alta potência com jarra de vidro",
    price: "R$ 249,90",
    image: "/placeholder.svg?key=duhlg",
    url: "https://www.exemplo.com/produto/2",
    quantity: 1,
    reserved: 0,
    eventId: "event-1",
  },
  {
    id: "gift-3",
    name: "Jogo de Cama Queen",
    description: "Jogo de cama 300 fios, 100% algodão",
    price: "R$ 299,90",
    image: "/cozy-bed-sheets.png",
    url: "https://www.exemplo.com/produto/3",
    quantity: 2,
    reserved: 1,
    eventId: "event-1",
  },
  {
    id: "gift-4",
    name: "Cafeteira Elétrica",
    description: "Cafeteira programável com jarra térmica",
    price: "R$ 349,90",
    image: "/modern-coffee-maker.png",
    url: "https://www.exemplo.com/produto/4",
    quantity: 1,
    reserved: 1,
    isPurchased: true,
    eventId: "event-2",
  },
  {
    id: "gift-5",
    name: "Conjunto de Taças",
    description: "Kit com 12 taças para vinho, água e champagne",
    price: "R$ 189,90",
    image: "/placeholder.svg?key=r7zw0",
    url: "https://www.exemplo.com/produto/5",
    quantity: 2,
    reserved: 0,
    eventId: "event-2",
  },
  {
    id: "gift-6",
    name: "Aspirador de Pó Robô",
    description: "Aspirador inteligente com mapeamento e controle por app",
    price: "R$ 1.299,90",
    image: "/robot-vacuum-cleaner.png",
    url: "https://www.exemplo.com/produto/6",
    quantity: 1,
    reserved: 0,
    eventId: "event-3",
  },
]

// Dados de exemplo para convidados
export const mockGuests: GuestType[] = [
  {
    id: "guest-1",
    name: "Carlos Silva",
    email: "carlos.silva@exemplo.com",
    status: "confirmed",
    message: "Parabéns pelo casamento! Estou ansioso para celebrar com vocês.",
    eventId: "event-1",
  },
  {
    id: "guest-2",
    name: "Ana Oliveira",
    email: "ana.oliveira@exemplo.com",
    status: "confirmed",
    message: "Que alegria poder participar deste momento tão especial!",
    eventId: "event-1",
  },
  {
    id: "guest-3",
    name: "Roberto Santos",
    email: "roberto.santos@exemplo.com",
    status: "declined",
    message: "Infelizmente não poderei comparecer, mas desejo toda felicidade do mundo!",
    eventId: "event-1",
  },
  {
    id: "guest-4",
    name: "Fernanda Lima",
    email: "fernanda.lima@exemplo.com",
    status: "pending",
    eventId: "event-1",
  },
  {
    id: "guest-5",
    name: "Marcelo Costa",
    email: "marcelo.costa@exemplo.com",
    status: "pending",
    eventId: "event-2",
  },
  {
    id: "guest-6",
    name: "Juliana Mendes",
    email: "juliana.mendes@exemplo.com",
    status: "confirmed",
    eventId: "event-2",
  },
  {
    id: "guest-7",
    name: "Ricardo Alves",
    email: "ricardo.alves@exemplo.com",
    status: "pending",
    eventId: "event-3",
  },
  {
    id: "guest-8",
    name: "Patrícia Gomes",
    email: "patricia.gomes@exemplo.com",
    status: "confirmed",
    eventId: "event-3",
  },
]
